services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: always
